### PR TITLE
gen-project for #14

### PR DESCRIPTION
**Pull request by turbomam**

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
I think `generated` is a new folder. shall we still with the current toplevel?

**Comment by turbomam** [comment]
> I think `generated` is a new folder. shall we still with the current toplevel?

I thought that was a lot of new files and folders to add to the current root

**Comment by turbomam** [comment]
I guess this isn't too bad

`ls -1 generated`

> excel
graphql
java
jsonld
jsonschema
mixs.py
owl
prefixmap
protobuf
shacl
shex
sqlschema

**Review by cmungall — APPROVED** [review]
OK, I guess we were keeping some of these at the top level before

We'll want to get rid of the existing jsonschema top level since it's now redundant with generated/jsonschema, but can be done in a separate PR

**Pull request merged**
